app:
  name: tips
  version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  version: v1.0

#maven.app: "@maven.build.artifactId@"

spring.liquibase.change-log: classpath:db/changeLog.sql

spring:
  config:
    additional-location: additional2.yml
    location: additional2.yml
  main:
    lazy-initialization: true
#    banner-mode: off
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: lazy